"""Generate CrewAI code from .papa AST — v0.3."""

from ..ast_nodes import AgentDef, PipelineDef, Program, SwarmDef

GUARD_VERBOSE = {"strict": False, "standard": True, "minimal": True}


def generate_crewai(program: Program, source_file: str = "") -> str:
    lines = [
        "# Auto-generated by papa-lang compiler v0.3.0",
        f"# Source: {source_file or 'unknown.papa'}",
        "# Target: CrewAI — DO NOT EDIT",
        "",
        "from crewai import Agent, Crew, Task, Process",
        "from papa_guard import Guard",
        "",
    ]
    for agent in program.agents:
        lines.extend(_gen_agent(agent))
    for swarm in program.swarms:
        lines.extend(_gen_crew(swarm))
    for pipeline in program.pipelines:
        lines.extend(_gen_flow(pipeline))
    return "\n".join(lines).rstrip() + "\n"


def _gen_agent(a: AgentDef) -> list:
    verbose = str(GUARD_VERBOSE.get(a.guard, True))
    return [
        f"{a.name}_guard = Guard(mode={a.guard!r})",
        f"{a.name}_agent = Agent(",
        f"    role={a.name!r},",
        f"    goal=f\"HRS < {a.hrs_threshold} — {a.guard} guard\",",
        f"    llm={a.model!r},",
        f"    verbose={verbose},",
        f"    memory={str(a.memory)},",
        f")",
        "",
    ]


def _gen_crew(s: SwarmDef) -> list:
    agents = "[" + ", ".join(f"{a}_agent" for a in s.agents) + "]"
    proc = "Process.hierarchical" if s.consensus else "Process.sequential"
    lines = [
        f"{s.name}_crew = Crew(",
        f"    agents={agents},",
        "    tasks=[],",
        f"    process={proc},",
        "    verbose=True,",
    ]
    if s.pii != "none":
        lines.append(f"    # pii: {s.pii}")
    lines += [")", ""]
    return lines


def _gen_flow(pipeline: PipelineDef) -> list:
    return [f"# Pipeline {pipeline.name} — run: {pipeline.name}_crew.kickoff()", ""]
