"""Microsoft Agent Framework (.NET) code generator for papa-lang v2.0."""

from ..ast_nodes import AgentDef, PipelineDef, Program, SwarmDef

GUARD_MAP = {
    "strict": {"tolerance": 0.10, "maxHrs": 0.20},
    "standard": {"tolerance": 0.15, "maxHrs": 0.30},
    "minimal": {"tolerance": 0.25, "maxHrs": 0.50},
}

MODEL_MAP = {
    "gpt-4o": "gpt-4o",
    "claude-3-sonnet": "claude-3-sonnet-20240229",
    "gemini-1.5-pro": "gemini-1.5-pro",
}


def generate_dotnet(program: Program, source_file: str = "") -> str:
    parts = [_header(source_file)]
    parts.append(_namespace_open())
    for agent in program.agents:
        parts.append(_gen_agent_class(agent))
    for swarm in program.swarms:
        parts.append(_gen_orchestrator_class(swarm, program))
    parts.append(_gen_program_main(program))
    parts.append(_namespace_close())
    return "\n".join(parts)


def _header(source_file: str) -> str:
    return f"""// Auto-generated by papa-lang compiler v2.0.0
// Source: {source_file or 'unknown.papa'}
// Target: Microsoft Agent Framework (.NET)
// DO NOT EDIT — regenerate with: papa compile <file>.papa --target dotnet

using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Agents;
using Microsoft.AI.Agents;
using PapaGuard;
"""


def _namespace_open() -> str:
    return "namespace PapaLang.Generated;"


def _gen_agent_class(agent: AgentDef) -> str:
    guard = GUARD_MAP.get(agent.guard, GUARD_MAP["standard"])
    model = MODEL_MAP.get(agent.model, agent.model)
    memory = "true" if agent.memory else "false"
    return f'''
/// <summary>papa-lang agent: {agent.name} | guard: {agent.guard} | hrs: {agent.hrs_threshold}</summary>
public class {_pascal(agent.name)}Agent : PapaAgentBase
{{
    public override string Name => "{agent.name}";
    public override string Model => "{model}";
    public override double HrsThreshold => {agent.hrs_threshold};
    public override string GuardLevel => "{agent.guard}";
    public override bool MemoryEnabled => {memory};

    private readonly Guard _guard = new Guard(
        mode: "{agent.guard}",
        passThreshold: {guard["tolerance"]},
        blockThreshold: {guard["maxHrs"]}
    );

    public {_pascal(agent.name)}Agent(Kernel kernel) : base(kernel) {{}}

    public override async Task<AgentResult> ExecuteAsync(string query)
    {{
        var response = await Kernel.InvokePromptAsync(query);
        var verdict = await _guard.EvaluateAsync(query, response.ToString());
        return new AgentResult {{ Response = response.ToString(), Verdict = verdict }};
    }}
}}
'''


def _gen_orchestrator_class(swarm: SwarmDef, program: Program) -> str:
    agents = ", ".join(f"new {_pascal(a)}Agent(kernel)" for a in swarm.agents)
    agents_list = "[" + ", ".join(f"typeof({_pascal(a)}Agent)" for a in swarm.agents) + "]"
    return f'''
public class {_pascal(swarm.name)}Orchestrator : PapaOrchestratorBase
{{
    public override Type[] AgentTypes => new[] {{ {agents_list} }};

    public {_pascal(swarm.name)}Orchestrator(Kernel kernel) : base(kernel) {{}}

    public override async Task<SwarmResult> OrchestrateAsync(string query)
    {{
        var agents = new IPapaAgent[] {{ {agents} }};
        return await RunSwarmAsync(agents, query);
    }}
}}
'''


def _gen_program_main(program: Program) -> str:
    return '''
public class PapaProgram
{
    public static async Task Main(string[] args)
    {
        var builder = Kernel.CreateBuilder();
        // Configure your AI service:
        // builder.AddOpenAIChatCompletion(modelId, apiKey);
        // builder.AddAzureOpenAIChatCompletion(deployment, endpoint, apiKey);
        var kernel = builder.Build();

        // papa-lang generated orchestrators are ready to use
        Console.WriteLine("papa-lang v2.0.0 — Microsoft Agent Framework");
    }
}
'''


def _namespace_close() -> str:
    return "// End of papa-lang generated code"


def _pascal(name: str) -> str:
    """Convert snake_case to PascalCase."""
    return "".join(w.capitalize() for w in name.split("_"))
