"""Generate Python from .papa AST using papa-lang SDK."""

from ..ast_nodes import AgentDef, PipelineDef, Program, SwarmDef


def _guard_args(guard: str) -> str:
    if guard == "strict":
        return "pii_enabled=True, injection_enabled=True"
    if guard == "minimal":
        return "pii_enabled=False, injection_enabled=False"
    return "pii_enabled=True, injection_enabled=True"


def _collect_imports(program: Program) -> list:
    extra = []
    for a in program.agents:
        if a.retrieval == "graph" and "from papa_lang.retrieval import GraphRetriever" not in extra:
            extra.append("from papa_lang.retrieval import GraphRetriever")
        if a.hrs_engine == "metaqa" and "from papa_guard.metaqa import MetaQAEngine" not in extra:
            extra.append("from papa_guard.metaqa import MetaQAEngine")
    for s in program.swarms:
        if s.pii == "presidio":
            extra.append("from papa_lang.pii import PresidioPIIFilter")
            break
        if s.pii in ("filter", "mask"):
            extra.append("from papa_lang.pii import MaskPIIFilter")
            break
    for s in program.swarms:
        if s.anchor == "blockchain":
            extra.append("from papa_guard.blockchain import get_anchor, make_record")
            break
    for p in program.pipelines:
        if p.observability != "none":
            extra.append("from papa_lang.observability import get_tracer")
            break
    return extra


class PythonGenerator:
    def generate(self, program: Program, source_file: str = "") -> str:
        base_imports = [
            "from papa_lang.orchestrator import Orchestrator",
            "from papa_lang.swarm import SwarmRunner, SwarmAgent, ConsensusConfig",
            "from papa_lang.hrs import HRSConfig",
            "from papa_guard import Guard",
        ]
        extra_imports = _collect_imports(program)
        all_imports = base_imports + extra_imports

        lines = [
            "# Auto-generated by papa-lang compiler v0.4.0",
            f"# Source: {source_file or 'unknown.papa'}",
            "# DO NOT EDIT — regenerate with: papa compile <file>.papa",
            "",
        ] + all_imports + [
            "",
            "# Agents",
        ]

        agent_vars = {}
        for a in program.agents:
            var = a.name
            agent_vars[a.name] = var
            guard_args = _guard_args(a.guard)
            retriever_arg = ""
            if a.retrieval == "graph":
                lines.append(f"{a.name}_retriever = GraphRetriever()")
                retriever_arg = f"\n    retriever={a.name}_retriever,"

            guard_inst = f"Guard({guard_args})"
            if a.hrs_engine == "metaqa":
                guard_inst = (
                    f'Guard(mode={a.guard!r}, hrs_engine="metaqa", '
                    "llm_call=your_llm_call_function)  # inject your LLM caller"
                )

            lines.append(
                f"{var} = SwarmAgent(\n"
                f"    name='{a.name}',\n"
                f"    model='{a.model}',\n"
                f"    guard={guard_inst},\n"
                f"    hrs_config=HRSConfig(threshold={a.hrs_threshold}),\n"
                f"    memory_enabled={a.memory},{retriever_arg}\n"
                f")"
            )
            lines.append("")

        if program.swarms:
            lines.append("# Swarms")
            for s in program.swarms:
                agent_refs = ", ".join(agent_vars.get(a, a) for a in s.agents)
                consensus_str = ""
                if s.consensus:
                    consensus_str = (
                        f"\n    consensus=ConsensusConfig("
                        f"required={s.consensus.required}, of={s.consensus.of}),"
                    )
                pii_bool = "True" if s.pii in ("filter", "mask", "presidio") else "False"

                if s.pii == "presidio":
                    lines.append(f"{s.name}_pii = PresidioPIIFilter()")
                elif s.pii in ("filter", "mask"):
                    lines.append(f"{s.name}_pii = MaskPIIFilter()")

                if s.anchor == "blockchain":
                    lines.append(f"{s.name}_anchor = get_anchor(")
                    lines.append('    "blockchain",')
                    lines.append('    # gateway_url="http://your-fabric-gateway:8080"  # production')
                    lines.append(")")
                    lines.append(
                        "# Usage: rec = make_record(agent_name, query, response, hrs, verdict, guard, model)"
                    )
                    lines.append(f"# tx_id = {s.name}_anchor.submit(rec)")
                    lines.append(f"# verified = {s.name}_anchor.verify(tx_id)")

                lines.append(
                    f"{s.name} = SwarmRunner(\n"
                    f"    name='{s.name}',\n"
                    f"    agents=[{agent_refs}],\n"
                    f"    anchor='{s.anchor}',\n"
                    f"    pii_filter={pii_bool},\n"
                    f"    hrs_max={s.hrs_max},{consensus_str}\n"
                    f")"
                )
                lines.append("")

        if program.pipelines:
            lines.append("# Pipeline")
            for p in program.pipelines:
                mod = f"'{p.module}'" if p.module else "''"
                obs_lines = []
                if p.observability != "none":
                    lines.append("from papa_lang.observability import get_tracer")
                    lines.append(f"{p.name}_tracer = get_tracer({p.observability!r})")
                    obs_lines = [f"# Usage: {p.name}_tracer.trace_agent(name, hrs, verdict)"]
                lines.append(
                    "orchestrator = Orchestrator(\n"
                    f"    route='{p.route}',\n"
                    f"    fallback='{p.fallback}',\n"
                    f"    module={mod},\n"
                    ")"
                )
                for ol in obs_lines:
                    lines.append(ol)

        return "\n".join(lines).rstrip() + "\n"
