"""Generate Python from .papa AST using papa-lang SDK."""

from ..ast_nodes import AgentDef, Program, SwarmDef


def _guard_args(guard: str) -> str:
    if guard == "strict":
        return "pii_enabled=True, injection_enabled=True"
    if guard == "minimal":
        return "pii_enabled=False, injection_enabled=False"
    return "pii_enabled=True, injection_enabled=True"


class PythonGenerator:
    def generate(self, program: Program, source_file: str = "") -> str:
        lines = [
            "# Auto-generated by papa-lang compiler v0.2.0",
            f"# Source: {source_file or 'unknown.papa'}",
            "# DO NOT EDIT — regenerate with: papa compile <file>.papa",
            "",
            "from papa_lang.orchestrator import Orchestrator",
            "from papa_lang.swarm import SwarmRunner, SwarmAgent, ConsensusConfig",
            "from papa_lang.hrs import HRSConfig",
            "from papa_guard import Guard",
            "",
            "# Agents",
        ]

        agent_vars = {}
        for a in program.agents:
            var = a.name
            agent_vars[a.name] = var
            guard_args = _guard_args(a.guard)
            lines.append(
                f"{var} = SwarmAgent(\n"
                f"    name='{a.name}',\n"
                f"    model='{a.model}',\n"
                f"    guard=Guard({guard_args}),\n"
                f"    hrs_config=HRSConfig(threshold={a.hrs_threshold}),\n"
                f"    memory_enabled={a.memory},\n"
                f")"
            )
            lines.append("")

        if program.swarms:
            lines.append("# Swarms")
            for s in program.swarms:
                agent_refs = ", ".join(agent_vars.get(a, a) for a in s.agents)
                consensus_str = ""
                if s.consensus:
                    consensus_str = (
                        f"\n    consensus=ConsensusConfig("
                        f"required={s.consensus.required}, of={s.consensus.of}),"
                    )
                pii = "True" if s.pii == "filter" else "False"
                lines.append(
                    f"{s.name} = SwarmRunner(\n"
                    f"    name='{s.name}',\n"
                    f"    agents=[{agent_refs}],\n"
                    f"    anchor='{s.anchor}',\n"
                    f"    pii_filter={pii},\n"
                    f"    hrs_max={s.hrs_max},{consensus_str}\n"
                    f")"
                )
                lines.append("")

        if program.pipelines:
            lines.append("# Pipeline")
            for p in program.pipelines:
                mod = f"'{p.module}'" if p.module else "''"
                lines.append(
                    "orchestrator = Orchestrator(\n"
                    f"    route='{p.route}',\n"
                    f"    fallback='{p.fallback}',\n"
                    f"    module={mod},\n"
                    ")"
                )

        return "\n".join(lines).rstrip() + "\n"
