"""Generate TypeScript from .papa AST using @papa-lang/core."""

from ..ast_nodes import AgentDef, Program, SwarmDef


class TypeScriptGenerator:
    def generate(self, program: Program, source_file: str = "") -> str:
        lines = [
            "// Auto-generated by papa-lang compiler v0.2.0",
            f"// Source: {source_file or 'unknown.papa'}",
            "// DO NOT EDIT — regenerate with: papa compile <file>.papa",
            "",
            "import { PapaClient, SwarmConfig, AgentConfig } from '@papa-lang/core'",
            "",
        ]

        agent_vars: dict = {}
        for a in program.agents:
            var = f"{a.name}Agent"
            agent_vars[a.name] = var
            lines.append(
                f"export const {var}: AgentConfig = {{\n"
                f"  name: '{a.name}',\n"
                f"  model: '{a.model}',\n"
                f"  guard: '{a.guard}',\n"
                f"  hrsThreshold: {a.hrs_threshold},\n"
                f"  memoryEnabled: {a.memory},\n"
                f"}}"
            )
            lines.append("")

        if program.swarms:
            for s in program.swarms:
                agent_refs = ", ".join(agent_vars.get(a, a) for a in s.agents)
                consensus_str = ""
                if s.consensus:
                    consensus_str = (
                        f"\n  consensus: {{ required: {s.consensus.required}, "
                        f"of: {s.consensus.of} }},"
                    )
                pii = "true" if s.pii == "filter" else "false"
                lines.append(
                    f"export const {s.name}: SwarmConfig = {{\n"
                    f"  name: '{s.name}',\n"
                    f"  agents: [{agent_refs}],\n"
                    f"  anchor: '{s.anchor}',\n"
                    f"  piiFilter: {pii},\n"
                    f"  hrsMax: {s.hrs_max},{consensus_str}\n"
                    f"}}"
                )
                lines.append("")

        return "\n".join(lines).rstrip() + "\n"
